spring:
  datasource:
    #url: jdbc:h2:tcp://localhost//D:/h2/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    url: jdbc:h2:file:D:/h2/test;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema.sql
#    data: classpath:db/schema.sql
