spring:
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: ALWAYS
      platform: h2
      tablePrefix: BATCH_
  datasource:
    #url: jdbc:h2:tcp://localhost//D:/h2/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    url: jdbc:h2:file:D:/h2/dev;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.H2Dialect
    open-in-view: false
  sql:
    init:
      mode: NEVER
      data-locations:
        - classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
        trace: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    contexts: test