spring:
  application:
    name: jpa-demo
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create-drop
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      # mode: always
      data-locations:
        - classpath:schema-BACK.sql
  sa-token:
    token-name: satoken
    timeout: 259200
    activity-timeout: -1
    allow-concurrent-login: false
    is-share: false
    token-style: uuid

logging:
  pattern:
    # 控制台日志格式
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(%-40.40logger{39}){cyan} : %msg%n"
