spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://10.10.10.190:5432/postgres
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate_ddl: true
    # map[string,string]
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: public
    open-in-view: false
  sql:
    init:
      mode: NEVER
      data-locations:
        - classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
        trace: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    contexts: test