spring:
  application:
    name: jpa-demo
  output:
    ansi:
      enabled: always
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update # create-drop
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  sql:
    init:
      # mode: always
      data-locations:
        - classpath:schema.sql
  datasource:
    #url: jdbc:h2:tcp://localhost//D:/h2/test;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE;AUTO_RECONNECT=TRUE;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL
    url: jdbc:h2:file:D:/h2/test;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
#    schema: classpath:db/schema.sql
#    data: classpath:db/schema.sql

logging:
  pattern:
    # 控制台日志格式
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(%-40.40logger{39}){cyan} : %msg%n"
