spring:
  output:
    ansi:
      enabled: always
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?currentSchema=public&allowMultiQueries=true&serverTimezone=UTC
#    url: jdbc:postgresql://10.10.10.190:5432/postgres
    username: postgres
    password: admin
#    password: root
    driver-class-name: org.postgresql.Driver
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
  jpa:
    show-sql: false
    defer-datasource-initialization: false
    hibernate:
      ddl-auto: none # auto create table if not exists
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate_ddl: false
    # map[string,string]
    properties:
      hibernate.format_sql: true
      hibernate.default_schema: public
    open-in-view: false
  sql:
    init:
      mode: NEVER
      data-locations:
        - classpath:data.sql
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: false
        trace: false
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    contexts: test
#p6spy:
#  config:
#    appender: com.p6spy.engine.spy.appender.Slf4JLogger
#    logMessageFormat: com.p6spy.engine.spy.appender.CustomLineFormat
#    customLogMessageFormat: executionTime:%(executionTime)| 执行sql:%(sqlSingleLine)

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE