spring:
  datasource:
    driver-class-name: org.h2.Driver
    #url: jdbc:h2:mem:test;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
    url: jdbc:h2:file:D:/h2/dev;DB_CLOSE_DELAY=-1;AUTO_RECONNECT=TRUE;MODE=PostgreSQL
    username: sa
    password:
  liquibase:
    enabled: true
    change-log: classpath:liquibase/master.xml
    # ???????
    database-change-log-table: databasechangelog
    # ??????lock?
    database-change-log-lock-table: databasechangeloglock
