CREATE TABLE IF NOT EXISTS pt_trigger(
    id varchar(50),
    ymd_id int,
    PARENT INT
);

CREATE TABLE IF NOT EXISTS PT_TEST (
    ID INT,
    NAME VARCHAR,
    LAST_MOD TIMESTAMP WITH TIME ZONE
        GENERATED ALWAYS AS CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS PT_ADDRESS;

CREATE TABLE IF NOT EXISTS PT_ADDRESS(
    ID BIGINT PRIMARY KEY,
    NAME VARCHAR,
    UPPER_NAME VARCHAR GENERATED ALWAYS AS UPPER(NAME),
    STATE VARCHAR,
    AGE INT DEFAULT 0
);
CREATE INDEX IF NOT EXISTS IDX_U_NAME ON PT_ADDRESS(UPPER_NAME);
CREATE SEQUENCE IF NOT EXISTS SEQ_PT_ADDRESS START WITH 3;