CREATE TABLE IF NOT EXISTS pt_trigger(
    id varchar(50),
    ymd_id int,
    PARENT INT
);

CREATE TABLE IF NOT EXISTS PT_TEST (
    ID INT,
    NAME VARCHAR,
    LAST_MOD TIMESTAMP WITH TIME ZONE
        GENERATED ALWAYS AS CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS PT_ADDRESS(
    ID INT PRIMARY KEY,
    NAME VARCHAR,
    UPPER_NAME VARCHAR GENERATED ALWAYS AS UPPER(NAME)
);
CREATE INDEX IDX_U_NAME ON PT_ADDRESS(UPPER_NAME);

INSERT INTO PT_ADDRESS(ID, NAME) VALUES(1, 'Miller');
SELECT * FROM PT_ADDRESS WHERE UPPER_NAME='MILLER';